### ISSUE TITLE
Create Account doesn't work

### ISSUE THREAD

**Issue by jstumbaugh** [Gooey-Dee-Bee/Ripple#111]
Every time I try it, I get a 500 Internal Server Error

**Comment by AveryFerrante** [comment]
On ec2 or on personal machine?

**Comment by jstumbaugh** [comment]
personal. It doesn't work on the master branch currently

**Comment by AveryFerrante** [comment]
Ya I made some changes to it Ill look into and have it fixed by tonight

**Comment by AveryFerrante** [comment]
Ok it is working for me. I know why it isn't working probably for everybody.
1. createAccount posts some stuff in some new tables so if you haven't vagranted up in a while, you probably should.
2. For the email service, im using some library called PHPMailer. You should see a folder for it in github PHP folder, but for some reason I don't think it is actually putting the files from inside the PHPMailer folder onto github, just the directory itself. The way to fix this is clone the PHPMailer github page. I can do this for people in class tomorrow.
3. Lastly, to send emails, I had to install something called sendmail (sudo apt-get install sendmail).

Overall, not a problem with the code, just annoying background configuration stuff
