### ISSUE TITLE
[EC2] Email Verification Email

### ISSUE THREAD

**Issue by jrutz** [Gooey-Dee-Bee/Ripple#121]
The "activate" link didn't work in mobile. 
Also on mobile, the second half of the "copy this link" is the only part which looks like a link (but it's not a full link) so it redirects you to an error. 

Is there a way to fix that? @AveryFerrante @jstumbaugh ? 

Our website is also super mobile unfriendly, but that's another issue completely and why we have an app.

**Comment by AveryFerrante** [comment]
Ya I need one of you HTML guru's to look at the email. It sends in HTML, and I thought I was doing the "a href" stuff right, but I guess not. Also, I haven't set this up yet, but the PHPMailer library will send a plain text to the email services that won't display HTML emails natively, so maybe that could eventually solve some of the problems? Jason and I can look at it if we meet tonight

**Comment by jstumbaugh** [comment]
I'm working on it now

**Comment by jstumbaugh** [comment]
So the link works in gmail, but for whatever reason, the mail app on macs attach some bs to the front of every link. Its an apple problem :/ I made it look pretty too.
