### ISSUE TITLE
People don't know what they're looking at

### ISSUE THREAD

**Issue by jrutz** [Gooey-Dee-Bee/Ripple#123]
We need to clarify the purpose of the website - whether it's on the homepage from 'create account' or a pop-up or something. 

People are confused about:
The geography (why certain songs are showing up)
Why it's anonymous
How many songs will show when/why
The purpose of the site - most people get that it's a 'sharing' site

Good news: 1 person got it to the core. Bad news: That's 1/9 people

**Comment by jstumbaugh** [comment]
added info page
