### ISSUE TITLE
Very Minor Issue In Graph Display

### ISSUE THREAD

**Issue by AveryFerrante** [Gooey-Dee-Bee/Ripple#135]
Graphs are looking good, I just noticed a small display error in the graphs to fix sometime in the future. From the picture, you can see what is returned from the PHP call. You can tell that the two lines ultimately have the same slope, but only one line is shown because (I assume) it is drawing over the other. Again, nothing pressing, just a small fix for the future.
![screenshot from 2015-05-09 00 29 25](https://cloud.githubusercontent.com/assets/5977374/7548873/c5e2e724-f5e2-11e4-81d7-b2eb5fc21744.png)

**Comment by jrutz** [comment]
Do you have a suggestion for an alternative? If the lines are the same they will be directly on top of each other.
