### ISSUE TITLE
Purchase Points

### ISSUE THREAD

**Issue by williamoconnor** [Gooey-Dee-Bee/Ripple#28]

**Comment by jrutz** [comment]
@williamoconnor are we good on purchasing?

**Comment by williamoconnor** [comment]
I actually realized when I was talking to Jason about it last week that we don't do anything on the backend, which might be necessary...not sure. I will look through the Stripe docs, but I will close this when it is all done

**Comment by AveryFerrante** [comment]
Ya Owen is working on a little PHP script for you to call when a user "purchases" points that stores some general info like how much they spent
