### ISSUE TITLE
Establish what the user gets from us [Pls Discuss]

### ISSUE THREAD

**Issue by jrutz** [Gooey-Dee-Bee/Ripple#36]
# Points
## What's the rate of exchange?
- Do songs with less drops on them cost less to drop again (T. Swizzle versus your favorite electro-punk-rapper)? That might give people incentive to drop lesser known songs. 
  con: we'd have to tell people how much each drop cost them before they actually dropped it. This takes time and takes away from the ease of it all.
- Can you spend more to drop a song further? 
- Should we give users a daily allowance of free songs (anywhere between 2-7) so we can encourage an active website rather than everyone waiting around for the next new thing so they won't have to buy more points?
## Should we make advanced preferences automatic?
- or should we keep the base uncluttered and have a pop-up module 'advanced' option for users that are totally obsessed and want four states to see their latest single?
# Geography
## Can the user see farther than their own circle?
- If so, can they pay more drops to drop in this circle?
- Should we have major city areas? Should we differentiate by genre? Should we throw darts at a map and pick whatever we hit? Should we pick zip codes we think sound cool?
# Account Profiles
## Do we even have them?

I mean, this isn't Facebook.
## What's in them?
- Maybe this is where users could buy more drops? (assuming at least 50% won't want to buy drops - think 'evernote premium' smooth where they don't push it in your face but you know about it)
- Have a 'saved drops' list so people can see what they've listened to over time? This would require a at least one more table that has the potential to get HUGE
- Have an option to export a list of your favorite songs a la text file so you can share playlists? OR just share the link to your full playlist? Good way to get more people to join. 
# Misc
## What would you want from an app like this?
- What would make you get on it in class when you can't listen to the music?
- What would make you want your friends to also get on it?
- What would make you talk to strangers about it? 

![cat-listening-music-wallpaper](https://cloud.githubusercontent.com/assets/5313865/7082059/0b877b0a-df13-11e4-9035-183945fd0df3.jpg)

For serious, everyone is doing great, only a few more weeks left.

**Comment by williamoconnor** [comment]
I think that we should make all drops cost the same, and as a general rule, I think if anything includes the word "advanced" we should leave it out. In a world where we are making this app with plans to continue working on it until it hits it big, we still need to release a version that is bare bones and just proves that the concept will work. I think that is what this project is

**Comment by jrutz** [comment]
Discussed in group meeting like two weeks ago*
