### ISSUE TITLE
Must refresh index.html to login

### ISSUE THREAD

**Issue by quincyschurr** [Gooey-Dee-Bee/Ripple#39]
Quincy Schurr
qschurr@smu.edu

When a user enters their email and password to login they receive an error message, but when they refresh the page it redirects to a page where their email has been loaded.

![screen shot 2015-04-11 at 4 20 55 pm](https://cloud.githubusercontent.com/assets/8551481/7103330/517e7622-e067-11e4-9773-e15596f0be4d.png)
![screen shot 2015-04-11 at 4 22 40 pm](https://cloud.githubusercontent.com/assets/8551481/7103331/540603b0-e067-11e4-81f6-32650f629216.png)

**Comment by jrutz** [comment]
@quincyschurr Was this from the index or from the landing page? I can't seem to replicate the error.

**Comment by quincyschurr** [comment]
@jrutz This was from the index. So when you first get to the page and attempt to log in you receive the first error and then when the page is refreshed it reloads the second picture.

**Comment by jrutz** [comment]
Would you mind trying again to confirm that it's still happening on your side? 
http://54.69.13.79/Ripple/website/index.html

**Comment by quincyschurr** [comment]
@jrutz I am still getting a similar error except now it says "account not found" but when I refresh my email shows up. I can now see a few soundclound songs showing up on the page, but there is no registration for me to have a true account.
