### ISSUE TITLE
Not everyone can be named Leonard Paton

### ISSUE THREAD

**Issue by jrutz** [Gooey-Dee-Bee/Ripple#6]
Pulling from (mock or real) database post-login to fill in these areas

![screen shot 2015-03-20 at 4 38 35 pm](https://cloud.githubusercontent.com/assets/5313865/6761313/a733358e-cf1f-11e4-918a-4fb5b52fa494.png)

**Comment by quincyschurr** [comment]
I'm assuming this issue goes with the iteration 1 feature of "creating an account" - Story ID S000.
