### ISSUE TITLE
Functional logout button

### ISSUE THREAD

**Issue by jrutz** [Gooey-Dee-Bee/Ripple#7]
Because our site is awesome, but I'm pretty sure there's some anti-spam law about never being able to log out.

![screen shot 2015-03-20 at 4 38 35 pm](https://cloud.githubusercontent.com/assets/5313865/6761332/df96618a-cf1f-11e4-8c1b-fd8f9b9a187c.png)

**Comment by williamoconnor** [comment]
Need to have actual session management and users
