### ISSUE TITLE
bumpSong no longer works :(

### ISSUE THREAD

**Issue by jstumbaugh** [Gooey-Dee-Bee/Ripple#71]

**Comment by jrutz** [comment]
@AveryFerrante Said they'd been messing with the reDrop and were/are in the process of sorting it out

**Comment by AveryFerrante** [comment]
It will be fixed by the end of today at the latest

**Comment by jrutz** [comment]
@AveryFerrante Fixed?

**Comment by AveryFerrante** [comment]
Pretty sure this is fixed. Still working on some other aspects of reDroping, but redroping will now load the song at the top of the list for sure.
