### ISSUE TITLE
Some View Account menu options don't work

### ISSUE THREAD

**Issue by AlyssaR** [Gooey-Dee-Bee/Ripple#78]
Once logged in, if you click "View Account" there are two options that don't work. 
1) Buy More Drops
![i want more drops](https://cloud.githubusercontent.com/assets/6731550/7334622/5866e8a0-eb5e-11e4-9908-22db98363979.PNG)

2) "Close"/X Button 
![go away i said](https://cloud.githubusercontent.com/assets/6731550/7334626/604548be-eb5e-11e4-9c2d-3d0f44e01856.PNG)

On closer inspection, I think it's because those 2 functions are commented out for some reason in userAccount.js. And it's a shame because all these alert and debug messages are golden.

**Comment by jrutz** [comment]
Our bad, EC2 was updated on Sunday...
