### ISSUE TITLE
What's a console?

### ISSUE THREAD

**Issue by AlyssaR** [Gooey-Dee-Bee/Ripple#79]
Anytime I login (any page), an alert tells me it worked but also to "check the console". I'm a user, though, so that whole console thing sounds scary. Should probably be taken out?

![1 check console](https://cloud.githubusercontent.com/assets/6731550/7334642/c1e64a1e-eb5e-11e4-8ce2-82cca3de3e70.PNG)

**Comment by jrutz** [comment]
Scaring the user is not our intent
