### ISSUE TITLE
Trapped on the Personal Playlist Page 

### ISSUE THREAD

**Issue by AlyssaR** [Gooey-Dee-Bee/Ripple#80]
On the main page, I can click View Account > View Drop History, and I'm taken to my Personal Playlist page. Once I'm there, though, I can no longer add songs and I can't go back to main (without clicking the back arrow in my browser, but who thinks about that?).

I think making the Ripple text a link to home would be helpful for user experience. That was my default reaction to go back at least.

**Comment by jrutz** [comment]
The header was established as a link a few days ago, can you reaffirm that it's still not working?

**Comment by AlyssaR** [comment]
The site was updated yesterday, and now the link is there and working!
