### ISSUE TITLE
Where are the songs? Also it doesn't know where I am

### ISSUE THREAD

**Issue by AlyssaR** [Gooey-Dee-Bee/Ripple#81]
Once logged in, there are no options to drop songs. I tried the home page and my personal playlist (basically any option on the menu) and none of them led to a page with songs. I noticed on the home page it endlessly looped looking for my location, so perhaps it has to find my location before I can drop things? 

![6 how iz i drop things](https://cloud.githubusercontent.com/assets/6731550/7339177/f857b372-ec2a-11e4-92a6-64d3a6662923.PNG)

**Comment by jrutz** [comment]
It shouldn't load any songs before it finds your location, that being said, how long did you wait/which browser are you using/did it ever find your location?

**Comment by AlyssaR** [comment]
My bad! I tried both Chrome and Firefox (on Windows). I realized that by default both browsers block location sharing. Once I enabled it, it worked.
