### ISSUE TITLE
Only re-dropped songs show on profile

### ISSUE THREAD

**Issue by quincyschurr** [Gooey-Dee-Bee/Ripple#83]
For me, the songs that I have dropped and re-dropped do not always appear on my Drop History page. For example in this first picture, I dropped the 1st song, re-dropped the 2nd song and dropped the 3rd song, but my drop history shows a duplicate of the first song and nothing about the 3rd song.

![screen shot 2015-04-26 at 7 20 08 pm](https://cloud.githubusercontent.com/assets/8551481/7340028/4abf2258-ec49-11e4-9e1d-dcb4a6a2de17.png)
![screen shot 2015-04-26 at 7 19 55 pm](https://cloud.githubusercontent.com/assets/8551481/7340030/4d412be8-ec49-11e4-991c-df3ed9b64e9c.png)

**Comment by jrutz** [comment]
Re-drops && searched drops are now showing without duplication
