### ISSUE TITLE
Question - logistics

### ISSUE THREAD

**Issue by quincyschurr** [Gooey-Dee-Bee/Ripple#84]
Is there supposed to be a way to see other users' profiles? Also are all the songs on the main page just the most dropped/re-dropped songs in my area? Is there a way to check out the best songs in other locations?

**Comment by jrutz** [comment]
We have an analytics page which shows you user usage based on email addresses. Besides that, we're focusing on music sharing anonymously to initiate a FairPlay sharing system that isn't bogged down with personalities or constructs that don't involve the music itself. 
The songs are ordered by recency in your area. 
Other locations may be in a future (post semester) iteration, but we may not get to that this month. 
Great questions!
