### ISSUE TITLE
Error creating account

### ISSUE THREAD

**Issue by cknee217** [Gooey-Dee-Bee/Ripple#86]
Can't create an account. Maybe put a better error message so the user knows what they did wrong

![screen shot 2015-04-27 at 10 44 29 am](https://cloud.githubusercontent.com/assets/8548541/7351402/913576ac-ecca-11e4-80d9-c9d558c75bff.png)

**Comment by AveryFerrante** [comment]
I left a comment on another issue you logged. I'm nearly certain all of these issues arise because you have downloaded our files and you are running them locally. You need to go to our ec2 URL which is 54.69.13.79/ripple/
