### ISSUE TITLE
Create Account Error Message

### ISSUE THREAD

**Issue by jrutz** [Gooey-Dee-Bee/Ripple#91]
Should be more specific - 
- If it's an email issue
- password matching
- whatever could invalidate it
  ![unknown](https://cloud.githubusercontent.com/assets/5313865/7361504/0920e74c-ed1f-11e4-8e34-53559fb3b457.png)
- possibly clear/make it a different color on second attempt, as is the error message just stays there

**Comment by AveryFerrante** [comment]
If the email address is already in use, the PHP will respond with 200 just FYI. I also think there should be some basic regex checking to make sure it is a "valid" email address
