### ISSUE TITLE
More than 10 songs showing at a time

### ISSUE THREAD

**Issue by AveryFerrante** [Gooey-Dee-Bee/Ripple#92]
Not sure how the group feels about this, but as of now we are limiting the song feed to the top 10. If you drop a new song from the search feature (and maybe from posting a soundcloud link, I haven't tested that), it goes to the top without removing the bottom song, so there are 11 total displayed. Refreshing fixes this. Not sure what we want to do about this

**Comment by AveryFerrante** [comment]
Ya, posting a link from soundcloud also just appends to the top of the list

**Comment by jrutz** [comment]
It might be nice if we showed more than 10 songs (like maybe 30/40/50), if people are listening straight through I can see how they wouldn't want to be refreshing the page for more songs.

I'll adjust the addSong functionality.

**Comment by AveryFerrante** [comment]
I agree, wasn't sure if we wanted to load 10 at a time and let the user click like a "load more" button or just return like 40 songs. Returning a lot of songs would be much easier, literally changing like 1 line of code. I think I'll just do that here in like 30 mins. Adjust the addSong thing to handle that if you need to.
